import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// @ts-expect-error process is a nodejs global
const host = process.env.TAURI_DEV_HOST;

/**
 * Vite plugin that provides a virtual module stub for the Tauri API when
 * running in a browser / web-only environment. This lets the codebase
 * import '@tauri-apps/api/tauri' dynamically in the app while avoiding
 * Vite failing to resolve that dependency in web dev.
 *
 * The stub simply exports a minimal `invoke` that throws a clear error when
 * called in the browser (so developers see a helpful message). Inside Tauri
 * runtime the real package will be present and the plugin resolve is skipped
 * because the runtime import will load the real module.
 */
function tauriWebStubPlugin() {
  const virtualId = "virtual:tauri-stub";
  return {
    name: "tauri-web-stub",
    resolveId(source) {
      // Redirect imports of the actual Tauri package to our virtual stub during web builds
      if (source === "@tauri-apps/api/tauri") {
        return virtualId;
      }
      return null;
    },
    load(id) {
      if (id === virtualId) {
        // Provide a minimal JS module as a string. Keep it intentionally small and clear.
        return `
          // Minimal Tauri web stub generated by Vite plugin.
          // Attempting to call invoke in a web-only environment will throw with a helpful message.
          export async function invoke(cmd, payload) {
            throw new Error(
              "[Tauri stub] '@tauri-apps/api/tauri' is not available in the browser. " +
              "Tried to invoke: " + (cmd || "<unknown>") + ". " +
              "Run inside Tauri (pnpm tauri dev / tauri build) to use native commands."
            );
          }
          // Export default and a flag for compatibility
          export const __TAURI__ = false;
          export default { invoke };
        `;
      }
      return null;
    },
  };
}

// https://vite.dev/config/
export default defineConfig(async () => ({
  plugins: [react(), tauriWebStubPlugin()],

  // Vite options tailored for Tauri development and only applied in `tauri dev` or `tauri build`
  //
  // 1. prevent Vite from obscuring rust errors
  clearScreen: false,
  // 2. tauri expects a fixed port, fail if that port is not available
  server: {
    port: 1420,
    strictPort: true,
    host: host || false,
    hmr: host
      ? {
          protocol: "ws",
          host,
          port: 1421,
        }
      : undefined,
    watch: {
      // 3. tell Vite to ignore watching `src-tauri`
      ignored: ["**/src-tauri/**"],
    },
  },
}));
